---
- name: Deploy Multiple WARs to {{ env_prefix | upper() }} Environment
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    tomcat_service: tomcat
    tomcat_home: /opt/tomcat9
    webapps_dir: "{{ tomcat_home }}/webapps"
    env_prefix: "{{ env_prefix | default('test') }}"

  tasks:
   - name: Find WAR files in workspace
  find:
    paths: .
    patterns: "wars/*.war"
    recurse: yes
    file_type: file
  delegate_to: localhost
  run_once: true
  register: controller_war_files

    - name: Debug - WARs found on controller
      debug:
        msg: "Found {{ controller_war_files.files | length }} WARs: {{ controller_war_files.files | map(attribute='path') | list }}"

    - name: Fail if no WARs
      fail:
        msg: "No WARs found in /root/multi-env-pipeline"
      when: controller_war_files.files | length == 0

    - name: Stop Tomcat before deployment
      systemd:
        name: "{{ tomcat_service }}"
        state: stopped

    - name: Cleanup old WARs
      file:
        path: "{{ webapps_dir }}/{{ env_prefix }}-*.war"
        state: absent

    - name: Cleanup exploded directories
      file:
        path: "{{ webapps_dir }}/{{ env_prefix }}-*/"
        state: absent

    - name: Deploy ALL WARs from controller
      copy:
        src: "{{ item.path }}"
        dest: "{{ webapps_dir }}/{{ env_prefix }}-{{ item.path | basename | regex_replace('.war$', '') }}.war"
        owner: tomcat
        group: tomcat
        mode: '0644'
        backup: yes
      loop: "{{ controller_war_files.files }}"
      notify: restart tomcat

  handlers:
    - name: restart tomcat
      systemd:
        name: "{{ tomcat_service }}"
        state: started

