---
- name: Deploy WAR to Tomcat9 (Multi-Environment)
  hosts: "{{ target_group | default('tomcat_servers') }}"
  become: yes
  gather_facts: yes
  
  vars:
    tomcat_service: tomcat
    tomcat_home: /opt/tomcat9
    webapps_dir: "{{ tomcat_home }}/webapps"
    war_dest_name: "{{ env_prefix }}-{{ war_file | basename | regex_replace('.war$', '') }}"

  tasks:
    - name: Validate required variables
      assert:
        that:
          - war_file is defined
          - env_prefix is defined
        fail_msg: "Missing vars: war_file={{ war_file }}, env_prefix={{ env_prefix }}"

    - name: Stop Tomcat
      systemd:
        name: "{{ tomcat_service }}"
        state: stopped
      register: tomcat_stopped

    - name: Cleanup old deployment (WAR + exploded folder)
      file:
        path: "{{ webapps_dir }}/{{ war_dest_name }}"
        state: absent

    - name: Cleanup old WAR
      file:
        path: "{{ webapps_dir }}/{{ war_dest_name }}.war"
        state: absent

    - name: Copy WAR with ENV prefix
      copy:
        src: "{{ war_file }}"
        dest: "{{ webapps_dir }}/{{ war_dest_name }}.war"
        owner: tomcat
        group: tomcat
        mode: '0644'
      register: war_deployed

    - name: Verify WAR deployed
      stat:
        path: "{{ webapps_dir }}/{{ war_dest_name }}.war"
      register: war_check

    - name: Show deployment status
      debug:
        msg: |
          WAR Status:
          - Copied: {{ war_deployed.changed }}
          - Exists: {{ war_check.stat.exists }}
          - Size: {{ war_check.stat.size | default('N/A') }} bytes
          - Path: {{ webapps_dir }}/{{ war_dest_name }}.war

    - name: Wait 30s for WAR explosion
      pause:
        minutes: 0.5
      when: war_check.stat.exists | bool

    - name: Health check (optional - ignore failures)
      uri:
        url: "http://{{ ansible_host }}:8080/{{ war_dest_name }}"
        status_code: [200, 302, 404]  # ✅ FIXED: status_code not status
        return_content: yes
        timeout: 30
      register: health_check
      ignore_errors: yes  # ✅ Continue even if app not ready

    - name: Start Tomcat
      systemd:
        name: "{{ tomcat_service }}"
        state: started
        enabled: yes
      register: tomcat_started

    - name: Wait for Tomcat startup
      wait_for:
        host: "{{ ansible_host }}"
        port: 8080
        delay: 10
        timeout: 60

    - name: Final deployment report
      debug:
        msg: |
          🎉 DEPLOYMENT COMPLETE!
          WAR: {{ war_dest_name }}.war ({{ war_check.stat.size | default('unknown') }} bytes)
          URL: http://{{ ansible_host }}:8080/{{ war_dest_name }}
          Tomcat: {{ tomcat_started.state | default('running') }}
          Health: {{ health_check.status | default('unchecked') }} ({{ health_check.msg | default('OK') }})

