---
- name: Deploy Multiple WARs to {{ env_prefix | upper() }} Environment
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    tomcat_service: tomcat
    tomcat_home: /opt/tomcat9
    webapps_dir: "{{ tomcat_home }}/webapps"
    env_prefix: "{{ env_prefix | default('test') }}"
    war_files:
      - path: "/var/lib/jenkins/jobs/multi-env-pipeline/workspace/wars/supermarket.war"
      - path: "/var/lib/jenkins/jobs/multi-env-pipeline/workspace/wars/sample.war"
      - path: "/var/lib/jenkins/jobs/multi-env-pipeline/workspace/wars/TestServerKrishna.war"

  tasks:
    - name: Debug - WARs ready for deployment
      debug:
        msg: "Deploying {{ war_files | length }} WARs to {{ env_prefix }} environment"

    - name: Stop Tomcat before deployment
      systemd:
        name: "{{ tomcat_service }}"
        state: stopped

    - name: Cleanup old WARs
      file:
        path: "{{ webapps_dir }}/{{ env_prefix }}-*.war"
        state: absent

    - name: Cleanup exploded directories
      file:
        path: "{{ webapps_dir }}/{{ env_prefix }}-*/"
        state: absent

    - name: Deploy ALL WARs from Jenkins workspace
      copy:
        src: "{{ item.path }}"
        dest: "{{ webapps_dir }}/{{ env_prefix }}-{{ item.path | basename | regex_replace('.war$', '') }}.war"
        owner: tomcat
        group: tomcat
        mode: '0644'
        backup: yes
      loop: "{{ war_files }}"
      notify: restart tomcat

  handlers:
    - name: restart tomcat
      systemd:
        name: "{{ tomcat_service }}"
        state: started
